CREATE TABLE IF NOT EXISTS mpa (
	mpa_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(200) NOT NULL,
	CONSTRAINT mpa_pk PRIMARY KEY (mpa_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS primary_key_mpa ON mpa (mpa_id);

CREATE TABLE IF NOT EXISTS films (
	film_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(200) NOT NULL,
	"description" varchar(200) NOT NULL,
	release_date date NOT NULL,
	duration int4 NOT NULL,
	mpa_id int4 NOT NULL,
	CONSTRAINT films_pk PRIMARY KEY (film_id),
	CONSTRAINT films_fk FOREIGN KEY (mpa_id) REFERENCES mpa(mpa_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS primary_key_film ON films (film_id);

CREATE TABLE IF NOT EXISTS genres (
	genre_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(200) NOT NULL,
	CONSTRAINT genres_pk PRIMARY KEY (genre_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS primary_key_genre ON genres (genre_id);

CREATE TABLE IF NOT EXISTS genres_films (
	film_id int4 NOT NULL,
	genre_id int4 NOT NULL,
	CONSTRAINT genres_films_film_fk FOREIGN KEY (film_id) REFERENCES films(film_id),
	CONSTRAINT genres_films_genre_fk FOREIGN KEY (genre_id) REFERENCES genres(genre_id)
);

CREATE TABLE IF NOT EXISTS users (
	user_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"login" varchar(200) NOT NULL,
	"name" varchar(200) NOT NULL,
	birthday date NOT NULL,
	"email" varchar(200) NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (user_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS primary_key_user ON users (user_id);

CREATE TABLE IF NOT EXISTS friends_users (
	user_id int4 NOT NULL,
	friend_id int4 NOT NULL,
	CONSTRAINT friends_users_fk FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS likes_films (
	film_id int4 NOT NULL,
	user_id int4 NOT NULL,
	CONSTRAINT likes_films_film_fk FOREIGN KEY (film_id) REFERENCES films(film_id),
	CONSTRAINT likes_films_user_fk FOREIGN KEY (user_id) REFERENCES users(user_id)
);